"use client";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { CaretDown, ShareNetwork } from "@phosphor-icons/react";
import AnimatedTextRTL from "@/components/shared/AnimatedTextRTL";
import SaveButton from "@/components/reflect/SaveButton";
export default function VerseReflectionCard() {
  const [tafsirOpen, setTafsirOpen] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  return <motion.div initial={{ y: 60, opacity: 0, scale: 0.96 }} animate={{ y: 0, opacity: 1, scale: 1 }} transition={{ type: "spring", stiffness: 60, damping: 25, delay: 0.3 }} whileHover={{ y: -4 }} className="w-full max-w-[680px] mt-16 bg-white/[0.03] backdrop-blur-[24px] border border-white/10 rounded-[2.5rem] p-8 md:p-14 shadow-[inset_0_1px_0_rgba(255,255,255,0.06),_0_32px_64px_-16px_rgba(0,0,0,0.5)] transition-shadow duration-500 hover:shadow-[inset_0_1px_0_rgba(255,255,255,0.06),_0_32px_80px_-12px_rgba(0,0,0,0.6)]"><span className="font-sans text-[11px] tracking-[0.18em] uppercase text-[var(--text-3)] block mb-10">Al-Anbiya, Ayah 83</span><AnimatedTextRTL text="وَأَيُّوبَ إِذْ نَادَىٰ رَبَّهُ أَنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ" delay={0.5} /><hr className="border-white/5 my-8" /><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.5, duration: 1 }} className="font-sans text-base text-[var(--text-3)] italic text-right max-w-[52ch] ml-auto leading-relaxed">"And [mention] Job, when he called to his Lord, 'Indeed, adversity has touched me, and You are the most merciful of the merciful.'"</motion.p><div className="mt-10 pt-6 border-t border-white/5"><button onClick={() => setTafsirOpen(!tafsirOpen)} className="flex items-center gap-2 text-[13px] font-medium text-[var(--text-3)] hover:text-[var(--parchment)] transition-colors w-full">View Tafsir <CaretDown weight="regular" size={14} className={`transform transition-transform ${tafsirOpen ? "rotate-180" : ""}`} /></button><AnimatePresence>{tafsirOpen && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><p className="font-sans text-[13px] text-[var(--text-3)] leading-[1.9] pt-4">This verse captures the profound patience of Prophet Ayyub (Job) during extreme physical illness and loss. Rather than complaining, his supplication is characterized by profound courtesy to Allah.</p></motion.div>}</AnimatePresence></div><div className="flex justify-between items-center mt-12 pt-6 border-t border-white/5"><button className="flex items-center gap-2 px-4 py-2 text-sm text-[var(--text-3)] hover:text-white transition-colors rounded-full hover:bg-white/5"><ShareNetwork weight="regular" size={16} /> Share Reflection</button><SaveButton isSaved={isSaved} onSave={() => setIsSaved(true)} /></div></motion.div>;
}
